apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-headless
  name: mysql-headless
  namespace: ivolve
spec:
  clusterIP: None
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-headless
  type: ClusterIP
status:
  loadBalancer: {}
