apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernets-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernets-app
  template:
    metadata:
      labels:
        app: kubernets-app
    spec:
      containers:
      - name: kubernets-app
        image: anas587/kubernets-app-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernets-app-service
spec:
  selector:
    app: kubernets-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer